# -*- coding: utf-8 -*-
"""Week 1 _Subj1200

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qT2bsq0hOj-ZF0DxnZ2KKtbcjB5ynQoB
"""

firstname= 'Cristian'
print(firstname)
print(type(firstname))
print('The first name is',firstname)

age= 27
print(age)
print(type(age))

#Of the notebook
#Funtion print
variable = "Python is Awesome!"
print(variable)

#With character
country = "Japan"
print("Tokyo is the capital city of " + country)

#Activity
variable = 100
variable = "This is the value"
print(variable)

#With funtion Type (It shows the type of data)
name1 = "Michael"
age1 = 24
print(type(name1))
print(type(age1))

#Activity with TYPE
a = 0
b = 42.1
c = -912
d = "678"
e = 13513517
f = 0.0
g = -13.012

print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))

#COMMMENT
# Our first program to print "Hello World!"

variable_name = "World" # Change "variable_name" to your name
print("Hello " + variable_name + "!")

#If we add this # this will ignore all tthe funtion and turns into a simple comment
#variable_name = "World"
#print("Hello " + variable_name + "!")
print("The above two lines are ignored by Python.")




variable1=input('Enter a number')
print(type(int(variable1)))  #this int allows me to accept just numbers integer

#It also can communte math questions directly
print(69 + 5)

#If we want to use exponents, we can add double **
print(2 ** 12)

#Modulo
print(23 % 5)

#Plus equal
# it will print 105
distance = 100
distance += 5 # same as distance = distance + 5
print(distance)

#with words
# prints add words to the String added
message = "add words to the String"
message += " added" # same as message = message + " added"
print(message)

#MULTI LINE STRINGS
variable3 = """
I am trying to write
here
en multiple lines
:O
"""
print(variable3)