# -*- coding: utf-8 -*-
"""Week3_Sub1200

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18CmhwNkxKvCovZB9VD6-zI3xInVyIzwt
"""

#LISTS
student_names = ['Djuro','Dhenesh','Silva','Saud']
numbers=[100, 200, 500, 50]

sports = ['basketball', 'soccer', 'tennis', 'cricket']
print(sports)

#This is going to show us the index 1 in this case would be Jim
students = ['Jing', 'Jim', 'Kerrie', 'Rakesh']
print(students[1])

#PRACTICE
numbers_cristian= [3, 10, 25, 7, 50, 99, 1, 18]
print(numbers_cristian)

print(numbers_cristian[0])
print(numbers_cristian[1])
print(numbers_cristian[2])
print(numbers_cristian[3])
print(numbers_cristian[4])
print(numbers_cristian[5])
print(numbers_cristian[6])
print(numbers_cristian[7])


#Alist=[1,2,3,4,5]

#USING METHODS
Alist=[1,2,3,4,5,6,7,8]

#REMOVE we can remove the first item with the specified value
Alist.remove(8)
print(Alist)

#grades.remove(value)
grades = [35, 50, 65, 85]
grades.remove(35)
print(grades) # prints [50, 65, 85] it delete the specific value

#grades.pop(specific_index)
grades = [35, 50, 65, 85]
grades.pop(0)
print(grades) # prints [50, 65, 85] it is on the index 0

# del grades[specific_index]
grades = [35, 50, 65, 85]
del grades[0]
print(grades) # prints [50, 65, 85] it is on the index 0


#LEND count how many items there are on a list
print('USING LEND')
f1 = ["apple", "banana", "orange"]
print(f1)
print(len(f1))

#Two Dimensional (2D) Lists
#gradebook = [['Jing', 35], ['Jim', 50], ['Kerrie', 65], ['Rakesh', 85]]
gradebook = [
 ['Jing', 35],
 ['Jim', 50],
 ['Kerrie', 65],
 ['Rakesh', 85]
]


print(gradebook[1]) # prints ['Jim', 50] because there is the index
#print(gradebook[3][1])
#we are going to see differents ways to modify the same in this case ['Jing', 35]
#we are changing the age
gradebook[-4][1]=26
gradebook[-4][1]=26
gradebook[-4][-1]=26
print(gradebook)


#USING ZIP
print('USING ZIP') #Its for combine 2 lists
students1 = ['Jing', 'Jim', 'Kerrie', 'Rakesh']
grades1 = [35, 50, 65, 85]
gradebook_zip1 = list(zip(students1, grades1))  #I can NOT MODIFY, we can ORDERED
print(gradebook_zip1)


#Slicing Lists
print('USING SLICING')
nums = [0, 1, 2, 3, 4, 5, 6, 7, 8]
print(nums)
print(nums[-6:-2])  #It basically extrac a portion of the list

#SETS
print('USING SETS')
#It is UNORDERED
grades_set = {35, 50, 65, 85, 85, 85}
print(grades_set)

#DICTIONARY
print('USING DICTIONARY')
#Duplicates are not allowed and its changeable
gradebook_dict = {
 'Jing': 35,
 'Jim': 50,
 'Kerrie': 65,
 'Rakesh': 85
 }


gradebook_dict = {
 'Jing': {
    'address': 'Fake Rd',
    'student_id': 12345,
    'ass1_grade': 20,
    'ass2_grade': 15,
    'ass3_grade': 0,
    'final_grade': 35
 },
 'Jim': 50,
 'Kerrie': 65,
 'Rakesh': 85
 }

print(gradebook_dict)

#Another example
Another1 = {
    'Cristian': {
        'address': 'Gold Coast',
            'ID': 11502334,
            'Grade1Assessment': 20,
            'Grade2Assessment': 35,
            'Grade3Assessment': 8,

        },
    'Carlos':50,
}
print(Another1)