# -*- coding: utf-8 -*-
"""Week2_Sub1200

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11B6o7AqL2v51_0qBrdqVVign3vUplxWu
"""

#'TRYING PSEUDOCODE FOR DECIDE IF GO TO THE WORKSHOP MONDAY'
'''
DayOfWeek = 'Monday'
if DayOfWeek: =='Monday':
  print('Go to workshop')

else:
  print('Do not go to workshop')
'''

#PRACTICE 2

Varaibleforthis = int(input("Please enter an integer value without decimal points: "))

if Varaibleforthis == 50:
    print("The value is equal to 50")
else:
    print("The value is NOT equal to 50")